AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spark API - icici::creditcard
Resources:
  CreditcardFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: icici.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/creditcard-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  CreditcardApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: CreditcardApi
